appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FTh47SXKB1/2v3XY/m3HJ7zhA9QSxMavAhfQtUHrlzqrkAsZLU1t9Le+1J6jLqHsJ5qZ0j2XsL9W8ToehwsYiC1jv4Pg0JM5Qeqo9tweHLwsCFHZyOYvft3i56J7VfHrkmuMXltb5IXZUS0o4HWin/ZiswL1VOi+r1BMVITN9HEe2ODWgBH0jsj2LHanW7G+KYPHYL9eA0LaZUbRd9uIOTa5Wv/CR7UA4Wjh8laxmFt81jhmdJL+tjjuCJx5Lq1YdM1c5XWsSvNaVCtdwGJKRQyfPgfwlZj8iQVrUw3WY3hm6P0hGUuu08mDlrmC9wVoasfhfkBo7cv85AYqfK14l7mBWkZWLwawxJ+jlwbuxFS1Wr9lX/+avVcqH0Tri5rUn1ogAP4PkohA6f3/wP0s2pmb15x5V36dH+8I6wK4GN2AKOufd2CJByPz+GpcVjWEchj6kYoyDo+bh57pcjW4KvEsmk7d1eZbbg9ZvRZ70jW2kPKhNZnXk6ApBszhvCEh1sYR2irlf9feldcaWFxIk4DlO6WZWauidXNkG93w1M4Rh1ItJ2nFFHmYgc4byu06C1lcor0DdLA5bSFjVzHvlPIRer9KiM9rMyFx8DFtOIfi3lezaKeZFXUxacpbMfBMUitcE0wSW3tTwol7WdxicGEWq3jsHfu2uY75fiF42KQ=}
conda_forge_output_validation: true
